# Generated by Django 4.1 on 2023-05-14 01:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dr', '0004_alter_visitplan_business_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('fixed_reservation_day', models.DateField()),
                ('fixed_reservation_time', models.TimeField()),
                ('zip_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="郵便番号の入力規則例: 123-4433 →'1234567'", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('pref', models.CharField(max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('address', models.CharField(max_length=100, verbose_name='番地')),
                ('Buil_name', models.CharField(max_length=100, verbose_name='建物名・部屋番号')),
                ('priority', models.CharField(choices=[(1, '高'), (2, '中'), (3, '低')], max_length=1)),
                ('reservation_day', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('visitplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Dr.visitplan')),
            ],
        ),
    ]
