# Generated by Django 4.1 on 2023-05-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reservation_day',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='client',
            name='priority',
            field=models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=1),
        ),
    ]
