# Generated by Django 4.1 on 2023-05-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_reservation_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fixed_reservation_day',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fixed_reservation_time',
        ),
    ]
