# Generated by Django 4.1 on 2023-05-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('business_day', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='Dr.dr')),
            ],
        ),
    ]
