# Generated by Django 4.1 on 2023-06-11 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dr', '0004_alter_visitplan_business_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='Buil_name',
            field=models.CharField(default=1, max_length=100, verbose_name='建物名・部屋番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplan',
            name='address',
            field=models.CharField(default=123333, max_length=100, verbose_name='番地'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplan',
            name='city',
            field=models.CharField(default='川西市', max_length=100, verbose_name='市区町村'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplan',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='pref',
            field=models.CharField(default='兵庫県', max_length=50, verbose_name='都道府県'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplan',
            name='zip_code',
            field=models.CharField(default=6660017, max_length=7, validators=[django.core.validators.RegexValidator(message="郵便番号の入力規則例: 123-4433 →'1234567'", regex='^[0-9]+$')], verbose_name='郵便番号'),
            preserve_default=False,
        ),
    ]
