# Generated by Django 4.1 on 2023-06-11 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dr', '0005_visitplan_buil_name_visitplan_address_visitplan_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitplan',
            name='zip_code',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="郵便番号の入力規則例: 123-4433 →'1234567'", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
